"""empty message

Revision ID: 05d1d3d6ad2a
Revises: e5e60462867d
Create Date: 2022-12-01 01:37:50.707368

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05d1d3d6ad2a'
down_revision = 'e5e60462867d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Debt_Installment', sa.Column('payed', sa.String(length=1), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Debt_Installment', 'payed')
    # ### end Alembic commands ###
