"""empty message

Revision ID: 4a7d91a93338
Revises: e4f5c65f9400
Create Date: 2022-12-05 14:36:43.017343

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a7d91a93338'
down_revision = 'e4f5c65f9400'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Debt_Installment', 'id_user')
    op.add_column('Debts', sa.Column('id_user', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'Debts', 'Users', ['id_user'], ['id'])
    op.add_column('Payment_Methods', sa.Column('id_user', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'Payment_Methods', 'Users', ['id_user'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Payment_Methods', type_='foreignkey')
    op.drop_column('Payment_Methods', 'id_user')
    op.drop_constraint(None, 'Debts', type_='foreignkey')
    op.drop_column('Debts', 'id_user')
    op.add_column('Debt_Installment', sa.Column('id_user', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###
