"""empty message

Revision ID: 76c20c176e33
Revises: 05d1d3d6ad2a
Create Date: 2022-12-04 18:31:45.692348

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76c20c176e33'
down_revision = '05d1d3d6ad2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Perfil_User',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=True),
    sa.Column('nome', sa.String(length=60), nullable=True),
    sa.Column('sobrenome', sa.String(length=60), nullable=True),
    sa.Column('numero_telefone', sa.String(length=20), nullable=True),
    sa.Column('cep', sa.String(length=10), nullable=True),
    sa.Column('cidade', sa.String(length=60), nullable=True),
    sa.Column('uf', sa.String(length=60), nullable=True),
    sa.ForeignKeyConstraint(['id_user'], ['Users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Perfil_User')
    # ### end Alembic commands ###
