"""empty message

Revision ID: e4f5c65f9400
Revises: 76c20c176e33
Create Date: 2022-12-04 21:13:07.771012

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4f5c65f9400'
down_revision = '76c20c176e33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Perfil_User', sa.Column('endereco', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Perfil_User', 'endereco')
    # ### end Alembic commands ###
